# Generated by Django 5.1.2 on 2024-10-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_usercategorypreference_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercategorypreference',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usercategorypreference',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='genres',
            field=models.ManyToManyField(to='main.genre'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='UserCategoryPreference',
        ),
    ]
