# Generated by Django 5.1.2 on 2024-10-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_usercategorypreference_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currently_reading',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='read',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='want_to_read',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
