# Generated by Django 5.1.1 on 2024-10-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_booklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
