# Generated by Django 5.1.1 on 2024-10-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_booklist_last_accessed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklist',
            old_name='book',
            new_name='book_item',
        ),
    ]
