# Generated by Django 5.1.2 on 2024-11-02 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='pages_read',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('to_read', 'Want to Read'), ('currently_reading', 'Currently Reading'), ('read', 'Read'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('books', models.ManyToManyField(related_name='shelves', to='main.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
