# Generated by Django 5.1.2 on 2024-11-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_shelf_user_shelf_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
