# Generated by Django 5.1.1 on 2024-11-02 19:11

from django.db import migrations


def populate_booklist(apps, schema_editor):
    UserProfile = apps.get_model('main', 'UserProfile')
    Shelf = apps.get_model('main', 'Shelf')
    Book = apps.get_model('main', 'Book')
    BookList = apps.get_model('main', 'BookList')

    for user_profile in UserProfile.objects.all():
        # Get all books from the user's shelves
        shelves = Shelf.objects.filter(user_profile=user_profile)
        for shelf in shelves:
            for book in shelf.books.all():
                # Create a BookList entry for each book in the user's shelves
                BookList.objects.create(
                    user_profile=user_profile,
                    book_item=book,
                    list_type=shelf.category  # or use a suitable value depending on your logic
                )

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_shelf_name'),
    ]

    operations = [
        migrations.RunPython(populate_booklist),
    ]